name: CI/CD Pipeline

on:
  workflow_dispatch:  

jobs:
  build-and-push:
    runs-on: [self-hosted]  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

    - name: Change directory and build Docker image
      run: |
        cd /home/nasrullah_pandud1/dify/web
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      env:
        REGISTRY: ${{ secrets.ECR_REGISTRY }}
        REPOSITORY: llmops-dify-web
        IMAGE_TAG: ${{ github.sha }}

  deploy:
    runs-on: [self-hosted] 
    needs: build-and-push  

    steps:
    - name: SSH into VM and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |

          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
          
          cd /home/nasrullah_pandud1/dify/docker
          docker-compose pull
          
          docker-compose up -d
