name: CI/CD Pipeline

on:
  workflow_dispatch:  

jobs:
  build-and-push:
    runs-on: [self-hosted]  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        region: ap-southeast-1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: llmops-dify-web
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  deploy:
    runs-on: [self-hosted] 
    needs: build-and-push  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # - name: SSH into VM and Deploy
    #   uses: appleboy/ssh-action@v0.2.2
    #   with:
    #     host: ${{ secrets.VM_HOST }}
    #     username: ${{ secrets.VM_USER }}
    #     key: ${{ secrets.VM_SSH_KEY }}
    #     script: |
          
    #       aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
                    
    #       docker-compose up -d
